CREATE TABLE IF NOT EXISTS `Accounts` (
    `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `account_number` VARCHAR(12) NOT NULL UNIQUE,
    `user_id` INT NOT NULL,
    `balance` INT NOT NULL DEFAULT 0, 
    `account_type` VARCHAR(20) NOT NULL,
    `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `modified` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY(user_id) REFERENCES Users(id)
)